### ISSUE TITLE
Plex server will be running?

### ISSUE THREAD

**Issue by dnrvn** [Ali1/PlexLocalWOL#1]
Hi, 
I am coming from your previous project, Plex listen and WoL. With this installation, will the Plex server on the raspberry pi be running, or will it stop? If it will be running, will it consume cpu resources? I am asking because it will be installed on an older RPi2, along with a few other services...

**Comment by Ali1** [comment]
Yep it's always running so can cause you issues. You can check by just started Plex now for a few hours on your Pi and check to see how much resources it uses.

**Comment by dnrvn** [comment]
> Yep it's always running so can cause you issues. You can check by just started Plex now for a few hours on your Pi and check to see how much resources it uses.

Oh, ok. Would it be possible to adapt previous code to restart it every few hours (or even 1 hour) and then put it to sleep?

**Comment by Ali1** [comment]
Because it relies on the Plex log files, Plex must be running with Debug mode on (I believe that's the default).

This relies on the log files being updated by Plex to know when to send a WOL packet, rather than "Sniffing" like the previous app - which I felt was harder to debug.

If the old one has been working well for you, keep at it :)

**Comment by dnrvn** [comment]
> Because it relies on the Plex log files, Plex must be running with Debug mode on (I believe that's the default).
> 
> This relies on the log files being updated by Plex to know when to send a WOL packet, rather than "Sniffing" like the previous app - which I felt was harder to debug.
> 
> If the old one has been working well for you, keep at it :)

Yeah, it has, as I mentioned in your other project, however I am curious about trying this one as well! Will definitely give it a try on a separate RPi2 and come back with results.
